# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63aa6b0b14a7eb80a7eb5879d2243273"
name = "ShopOMS"
application_url = "https://shop-oms.vercel.app"
embedded = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_inventory,write_orders,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://shop-oms.vercel.app/api/auth/callback" ]
